recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    provider: self-hosted
    model: rasa/cmd_gen_llama_3.1_8b_calm_demo
    api_base: http://34.133.242.178:8000/v1
    timeout: 7
    max_tokens: 256
    temperature: 0
  flow_retrieval:
    active: false

policies:
- name: FlowPolicy
#  - name: EnterpriseSearchPolicy
#  - name: RulePolicy
assistant_id: 20241024-141452-salty-deed
